from __future__ import annotations

import argparse
import json
import math
import pickle
from pathlib import Path
from typing import Any


P4_FEATURES = (
    "Packet Length Max",
    "PSH Flag Count",
    "Total Length of Fwd Packet",
    "FIN Flag Count",
    "Fwd Packet Length Max",
    "Total Bwd packets",
)

P4_NAMES = {
    "Packet Length Max": "packet_length_max",
    "PSH Flag Count": "psh_flag_count",
    "Total Length of Fwd Packet": "total_fwd_length",
    "FIN Flag Count": "fin_flag_count",
    "Fwd Packet Length Max": "fwd_packet_length_max",
    "Total Bwd packets": "total_bwd_packets",
}

MAX_P4_VALUE = (1 << 16) - 1


def _compiler_from_pickle(path: Path) -> dict[str, Any]:
    payload = pickle.loads(path.read_bytes())
    if not isinstance(payload, dict) or "model" not in payload or "features" not in payload:
        raise ValueError("model pickle must contain 'model' and 'features'")
    model = payload["model"]
    features = list(payload["features"])
    classes = [str(label) for label in model.classes_]
    tree = model.tree_
    nodes = []
    thresholds: dict[str, set[float]] = {feature: set() for feature in features}
    for node_id in range(tree.node_count):
        feature_index = int(tree.feature[node_id])
        is_leaf = feature_index < 0
        feature = None if is_leaf else features[feature_index]
        threshold = None if is_leaf else float(tree.threshold[node_id])
        if feature is not None and threshold is not None:
            thresholds[feature].add(threshold)
        prediction = classes[int(tree.value[node_id][0].argmax())]
        nodes.append(
            {
                "node_id": node_id,
                "feature": feature,
                "threshold": threshold,
                "left_child": None if is_leaf else int(tree.children_left[node_id]),
                "right_child": None if is_leaf else int(tree.children_right[node_id]),
                "prediction": prediction,
                "is_leaf": is_leaf,
            }
        )
    return {
        "model": "StateDT",
        "features": features,
        "class_ids": {label: index for index, label in enumerate(classes)},
        "feature_specs": {
            feature: {"thresholds": sorted(thresholds[feature])} for feature in features
        },
        "tree": {"nodes": nodes},
    }


def _load_compiler(path: Path) -> dict[str, Any]:
    if path.suffix == ".pkl":
        return _compiler_from_pickle(path)
    return json.loads(path.read_text(encoding="utf-8"))


def _caps(compiler: dict[str, Any]) -> dict[str, int]:
    caps: dict[str, int] = {}
    specs = compiler["feature_specs"]
    for feature in P4_FEATURES:
        thresholds = specs[feature]["thresholds"]
        if not thresholds:
            raise ValueError(f"StateDT feature has no thresholds: {feature}")
        cap = math.floor(max(thresholds)) + 1
        if cap > MAX_P4_VALUE:
            raise ValueError(
                f"StateDT feature '{feature}' needs cap {cap}, above the 16-bit P4 limit"
            )
        caps[feature] = cap
    return caps


def _leaf_ranges(
    compiler: dict[str, Any], caps: dict[str, int]
) -> list[tuple[list[tuple[int, int]], int, int]]:
    nodes = {node["node_id"]: node for node in compiler["tree"]["nodes"]}
    class_ids = compiler["class_ids"]
    leaves: list[tuple[list[tuple[int, int]], int, int]] = []
    initial = {feature: (0, caps[feature]) for feature in P4_FEATURES}

    def visit(node_id: int, bounds: dict[str, tuple[int, int]]) -> None:
        node = nodes[node_id]
        if node["is_leaf"]:
            leaves.append(
                ([bounds[feature] for feature in P4_FEATURES], class_ids[node["prediction"]], node_id)
            )
            return

        feature = node["feature"]
        if feature not in bounds:
            raise ValueError(f"tree uses unsupported P4 feature: {feature}")
        low, high = bounds[feature]
        split = math.floor(node["threshold"])

        left_high = min(high, split)
        if low <= left_high:
            left = dict(bounds)
            left[feature] = (low, left_high)
            visit(node["left_child"], left)

        right_low = max(low, split + 1)
        if right_low <= high:
            right = dict(bounds)
            right[feature] = (right_low, high)
            visit(node["right_child"], right)

    visit(0, initial)
    return leaves


def _model_include(compiler: dict[str, Any], caps: dict[str, int], leaf_count: int) -> str:
    benign_id = compiler["class_ids"].get("Benign", 0)
    class_lines = [f"const bit<8> CLASS_BENIGN = 8w{benign_id};"]
    cap_lines = [
        f"const bit<16> CAP_{P4_NAMES[feature].upper()} = 16w{caps[feature]};"
        for feature in P4_FEATURES
    ]
    return "\n".join(
        [
            "// Generated by p4/tools/generate_statedt.py. Do not edit by hand.",
            f"const bit<32> STATEDT_RULE_COUNT = 32w{leaf_count};",
            *cap_lines,
            "",
            *class_lines,
            "",
        ]
    )


def _entries_include(leaves: list[tuple[list[tuple[int, int]], int, int]]) -> str:
    lines = ["// Generated by p4/tools/generate_statedt.py. Do not edit by hand."]
    for ranges, class_id, node_id in leaves:
        keys = ", ".join(f"16w{low} .. 16w{high}" for low, high in ranges)
        lines.append(f"({keys}) : set_class(8w{class_id}); // leaf {node_id}")
    lines.append("")
    return "\n".join(lines)


def _validate_partition(
    leaves: list[tuple[list[tuple[int, int]], int, int]], caps: dict[str, int]
) -> None:
    expected_volume = math.prod(caps[feature] + 1 for feature in P4_FEATURES)
    actual_volume = 0
    for ranges, _, node_id in leaves:
        if len(ranges) != len(P4_FEATURES):
            raise ValueError(f"leaf {node_id} has an invalid key dimension")
        volume = 1
        for (low, high), feature in zip(ranges, P4_FEATURES, strict=True):
            if low < 0 or high < low or high > caps[feature]:
                raise ValueError(f"leaf {node_id} has invalid bounds for {feature}: {low}..{high}")
            volume *= high - low + 1
        actual_volume += volume

    if actual_volume != expected_volume:
        raise ValueError(
            "generated leaf ranges do not cover the complete capped feature domain "
            f"({actual_volume} != {expected_volume})"
        )

    for index, (left, _, left_id) in enumerate(leaves):
        for right, _, right_id in leaves[index + 1 :]:
            if all(
                left_low <= right_high and right_low <= left_high
                for (left_low, left_high), (right_low, right_high) in zip(
                    left, right, strict=True
                )
            ):
                raise ValueError(f"generated leaf ranges overlap: {left_id} and {right_id}")


def generate(compiler_path: Path, output_dir: Path) -> tuple[Path, Path, Path, int]:
    compiler = _load_compiler(compiler_path)
    if compiler.get("model") != "StateDT":
        raise ValueError("compiler artifact is not a StateDT model")
    if tuple(compiler.get("features", ())) != P4_FEATURES:
        raise ValueError(
            "P4 targets require this exact StateDT feature order: " + ", ".join(P4_FEATURES)
        )
    caps = _caps(compiler)
    leaves = _leaf_ranges(compiler, caps)
    _validate_partition(leaves, caps)

    output_dir.mkdir(parents=True, exist_ok=True)
    model_path = output_dir / "statedt_model.p4inc"
    entries_path = output_dir / "statedt_entries.p4inc"
    classes_path = output_dir / "statedt_classes.json"
    model_path.write_text(_model_include(compiler, caps, len(leaves)), encoding="utf-8")
    entries_path.write_text(_entries_include(leaves), encoding="utf-8")
    classes_path.write_text(
        json.dumps(compiler["class_ids"], indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return model_path, entries_path, classes_path, len(leaves)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate StateDT P4 range-table includes")
    parser.add_argument("compiler", type=Path, help="StateDT compiler.json or model.pkl")
    parser.add_argument(
        "--output-dir", type=Path, default=Path("p4/common"), help="generated include directory"
    )
    args = parser.parse_args()
    model_path, entries_path, classes_path, count = generate(args.compiler, args.output_dir)
    print(
        f"generated {count} StateDT rules: {model_path}, {entries_path}, {classes_path}"
    )


if __name__ == "__main__":
    main()
