from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


P4_FEATURES = (
    "Packet Length Max",
    "PSH Flag Count",
    "Total Length of Fwd Packet",
    "FIN Flag Count",
    "Fwd Packet Length Max",
    "Total Bwd packets",
)

P4_NAMES = {
    "Packet Length Max": "packet_length_max",
    "PSH Flag Count": "psh_flag_count",
    "Total Length of Fwd Packet": "total_fwd_length",
    "FIN Flag Count": "fin_flag_count",
    "Fwd Packet Length Max": "fwd_packet_length_max",
    "Total Bwd packets": "total_bwd_packets",
}

MAX_P4_VALUE = (1 << 16) - 1


def _headers_include() -> str:
    return """// Generated by p4/tools/generate_statedt.py. Do not edit by hand.
const bit<16> ETHERTYPE_IPV4 = 16w0x0800;
const bit<16> ETHERTYPE_STATEDT = 16w0x88b5;
const bit<8> IP_PROTOCOL_TCP = 8w6;
const bit<8> IP_PROTOCOL_UDP = 8w17;

header ethernet_t {
    bit<48> dst_addr;
    bit<48> src_addr;
    bit<16> ether_type;
}

header ipv4_t {
    bit<4> version;
    bit<4> ihl;
    bit<8> diffserv;
    bit<16> total_len;
    bit<16> identification;
    bit<3> flags;
    bit<13> fragment_offset;
    bit<8> ttl;
    bit<8> protocol;
    bit<16> hdr_checksum;
    bit<32> src_addr;
    bit<32> dst_addr;
}

header tcp_t {
    bit<16> src_port;
    bit<16> dst_port;
    bit<32> seq_no;
    bit<32> ack_no;
    bit<4> data_offset;
    bit<3> reserved;
    bit<1> ns;
    bit<1> cwr;
    bit<1> ece;
    bit<1> urg;
    bit<1> ack;
    bit<1> psh;
    bit<1> rst;
    bit<1> syn;
    bit<1> fin;
    bit<16> window;
    bit<16> checksum;
    bit<16> urgent_ptr;
}

header udp_t {
    bit<16> src_port;
    bit<16> dst_port;
    bit<16> length;
    bit<16> checksum;
}

header statedt_result_t {
    bit<16> original_ether_type;
    bit<8> class_id;
    bit<1> state_valid;
    bit<7> reserved;
}

struct headers_t {
    ethernet_t ethernet;
    statedt_result_t result;
    ipv4_t ipv4;
    tcp_t tcp;
    udp_t udp;
}

struct flow_features_t {
    bit<16> packet_length_max;
    bit<16> psh_flag_count;
    bit<16> total_fwd_length;
    bit<16> fin_flag_count;
    bit<16> fwd_packet_length_max;
    bit<16> total_bwd_packets;
}
"""


def _load_compiler(path: Path) -> dict[str, Any]:
    if path.suffix != ".json":
        raise ValueError("StateDT P4 generation requires compiler.json")
    return json.loads(path.read_text(encoding="utf-8"))


def _caps(compiler: dict[str, Any]) -> dict[str, int]:
    caps: dict[str, int] = {}
    specs = compiler["feature_specs"]
    for feature in P4_FEATURES:
        spec = specs[feature]
        thresholds = spec["thresholds"]
        if not thresholds:
            raise ValueError(f"StateDT feature has no thresholds: {feature}")
        representation = spec.get("representation")
        if representation == "threshold_region":
            cap = int(spec["state_count"]) - 1
        elif representation == "capped_integer":
            cap = int(spec["cap"])
        else:
            raise ValueError(
                f"unsupported StateDT representation for {feature}: {representation!r}"
            )
        if cap > MAX_P4_VALUE:
            raise ValueError(
                f"StateDT feature '{feature}' needs cap {cap}, above the 16-bit P4 limit"
            )
        caps[feature] = cap
    return caps


def _state_layout(compiler: dict[str, Any]) -> dict[str, Any]:
    layout = compiler.get("state_layout")
    if not isinstance(layout, dict):
        raise ValueError("compiler artifact has no canonical state_layout")
    if layout.get("version") != 1 or layout.get("bit_order") != "lsb0":
        raise ValueError("unsupported StateDT state layout")

    fields = layout.get("fields")
    if not isinstance(fields, list) or not fields:
        raise ValueError("StateDT state layout has no fields")
    specs = compiler["feature_specs"]
    expected_offset = 0
    seen: set[str] = set()
    for field in fields:
        feature = field.get("feature")
        if feature in seen or feature not in specs:
            raise ValueError(f"invalid or duplicate layout feature: {feature!r}")
        seen.add(feature)
        width = int(field.get("width", -1))
        offset = int(field.get("offset", -1))
        spec = specs[feature]
        minimum_width = 0 if int(spec["state_count"]) == 1 else math.ceil(
            math.log2(int(spec["state_count"]))
        )
        if width != int(spec["logical_bits"]) or width != minimum_width:
            raise ValueError(f"invalid synthesized width for {feature}: {width}")
        if offset != expected_offset or field.get("lsb") != offset:
            raise ValueError(f"non-contiguous layout field: {feature}")
        expected_msb = offset + width - 1 if width else None
        if field.get("msb") != expected_msb:
            raise ValueError(f"invalid layout range for {feature}")
        if int(field.get("initial_state", -1)) != 0:
            raise ValueError(f"unsupported nonzero initial state for {feature}")
        expected_offset += width
    if seen != set(specs):
        raise ValueError("state layout does not cover every compiled feature")
    if int(layout.get("feature_state_bits", -1)) != expected_offset:
        raise ValueError("state layout width does not match its fields")
    if int(compiler.get("feature_state_bits", -1)) != expected_offset:
        raise ValueError("compiler feature_state_bits does not match state_layout")
    return layout


def _layout_include(layout: dict[str, Any]) -> str:
    feature_bits = int(layout["feature_state_bits"])
    lines = [
        "// Generated by p4/tools/generate_statedt.py. Do not edit by hand.",
        f"#define STATEDT_FEATURE_STATE_BITS {feature_bits}",
        f"#define STATEDT_FINGERPRINT_LSB {feature_bits}",
        f"#define STATEDT_FINGERPRINT_MSB {feature_bits + 15}",
        f"#define STATEDT_DIRECTION_BIT {feature_bits + 16}",
        f"#define STATEDT_VALID_BIT {feature_bits + 17}",
        f"#define STATEDT_BMV2_ENTRY_BITS {feature_bits + 18}",
    ]
    for field in layout["fields"]:
        name = P4_NAMES[field["feature"]].upper()
        lines.extend([
            f"#define WIDTH_{name} {field['width']}",
            f"#define OFFSET_{name} {field['offset']}",
        ])
    lines.append("")
    return "\n".join(lines)


def _state_access_include(layout: dict[str, Any], *, pack: bool) -> str:
    operation = "pack" if pack else "unpack"
    lines = [
        f"// Generated StateDT {operation}. Do not edit by hand.",
    ]
    for field in layout["fields"]:
        p4_name = P4_NAMES[field["feature"]]
        lsb = int(field["lsb"])
        msb = int(field["msb"])
        if pack:
            lines.append(
                f"meta.state[{msb}:{lsb}] = meta.features.{p4_name}[{field['width'] - 1}:0];"
            )
        else:
            lines.append(
                f"meta.features.{p4_name} = (bit<16>) meta.state[{msb}:{lsb}];"
            )
    lines.append("")
    return "\n".join(lines)


def _leaf_ranges(
    compiler: dict[str, Any], caps: dict[str, int]
) -> list[tuple[list[tuple[int, int]], int, int]]:
    nodes = {node["node_id"]: node for node in compiler["tree"]["nodes"]}
    class_ids = compiler["class_ids"]
    leaves: list[tuple[list[tuple[int, int]], int, int]] = []
    initial = {feature: (0, caps[feature]) for feature in P4_FEATURES}

    def visit(node_id: int, bounds: dict[str, tuple[int, int]]) -> None:
        node = nodes[node_id]
        if node["is_leaf"]:
            leaves.append(
                ([bounds[feature] for feature in P4_FEATURES], class_ids[node["prediction"]], node_id)
            )
            return

        feature = node["feature"]
        if feature not in bounds:
            raise ValueError(f"tree uses unsupported P4 feature: {feature}")
        low, high = bounds[feature]
        spec = compiler["feature_specs"][feature]
        if spec["representation"] == "threshold_region":
            split = spec["thresholds"].index(node["threshold"])
        else:
            split = math.floor(node["threshold"])

        left_high = min(high, split)
        if low <= left_high:
            left = dict(bounds)
            left[feature] = (low, left_high)
            visit(node["left_child"], left)

        right_low = max(low, split + 1)
        if right_low <= high:
            right = dict(bounds)
            right[feature] = (right_low, high)
            visit(node["right_child"], right)

    visit(0, initial)
    return leaves


def _model_include(compiler: dict[str, Any], caps: dict[str, int], leaf_count: int) -> str:
    benign_id = compiler["class_ids"].get("Benign", 0)
    class_lines = [f"const bit<8> CLASS_BENIGN = 8w{benign_id};"]
    cap_lines = [
        f"const bit<16> CAP_{P4_NAMES[feature].upper()} = 16w{caps[feature]};"
        for feature in P4_FEATURES
    ]
    return "\n".join(
        [
            "// Generated by p4/tools/generate_statedt.py. Do not edit by hand.",
            f"const bit<32> STATEDT_RULE_COUNT = 32w{leaf_count};",
            *cap_lines,
            "",
            *class_lines,
            "",
        ]
    )


def _entries_include(leaves: list[tuple[list[tuple[int, int]], int, int]]) -> str:
    lines = ["// Generated by p4/tools/generate_statedt.py. Do not edit by hand."]
    for ranges, class_id, node_id in leaves:
        keys = ", ".join(f"16w{low} .. 16w{high}" for low, high in ranges)
        lines.append(f"({keys}) : set_class(8w{class_id}); // leaf {node_id}")
    lines.append("")
    return "\n".join(lines)


def _validate_partition(
    leaves: list[tuple[list[tuple[int, int]], int, int]], caps: dict[str, int]
) -> None:
    expected_volume = math.prod(caps[feature] + 1 for feature in P4_FEATURES)
    actual_volume = 0
    for ranges, _, node_id in leaves:
        if len(ranges) != len(P4_FEATURES):
            raise ValueError(f"leaf {node_id} has an invalid key dimension")
        volume = 1
        for (low, high), feature in zip(ranges, P4_FEATURES, strict=True):
            if low < 0 or high < low or high > caps[feature]:
                raise ValueError(f"leaf {node_id} has invalid bounds for {feature}: {low}..{high}")
            volume *= high - low + 1
        actual_volume += volume

    if actual_volume != expected_volume:
        raise ValueError(
            "generated leaf ranges do not cover the complete capped feature domain "
            f"({actual_volume} != {expected_volume})"
        )

    for index, (left, _, left_id) in enumerate(leaves):
        for right, _, right_id in leaves[index + 1 :]:
            if all(
                left_low <= right_high and right_low <= left_high
                for (left_low, left_high), (right_low, right_high) in zip(
                    left, right, strict=True
                )
            ):
                raise ValueError(f"generated leaf ranges overlap: {left_id} and {right_id}")


def _max_update_include(compiler: dict[str, Any], feature: str, packet_expr: str) -> str:
    spec = compiler["feature_specs"][feature]
    if spec["representation"] != "threshold_region":
        raise ValueError(f"P4 max feature {feature!r} must use threshold_region")
    lines = ["incoming_region = 0;"]
    for index, threshold in enumerate(spec["thresholds"], start=1):
        lines.append(
            f"if ({packet_expr} > 16w{math.floor(threshold)}) {{ incoming_region = 16w{index}; }}"
        )
    return "\n".join(lines) + "\n"


def generate(compiler_path: Path, output_dir: Path) -> tuple[Path, Path, Path, int]:
    compiler = _load_compiler(compiler_path)
    if compiler.get("model") != "StateDT":
        raise ValueError("compiler artifact is not a StateDT model")
    if compiler.get("compiler") != "decision-sufficient-state":
        raise ValueError("compiler artifact is not decision-sufficient StateDT")
    if tuple(compiler.get("features", ())) != P4_FEATURES:
        raise ValueError(
            "P4 targets require this exact StateDT feature order: " + ", ".join(P4_FEATURES)
        )
    layout = _state_layout(compiler)
    caps = _caps(compiler)
    leaves = _leaf_ranges(compiler, caps)
    _validate_partition(leaves, caps)

    output_dir.mkdir(parents=True, exist_ok=True)
    model_path = output_dir / "statedt_model.p4inc"
    entries_path = output_dir / "statedt_entries.p4inc"
    classes_path = output_dir / "statedt_classes.json"
    layout_path = output_dir / "statedt_layout.json"
    (output_dir / "statedt_headers.p4").write_text(
        _headers_include(), encoding="utf-8"
    )
    model_path.write_text(_model_include(compiler, caps, len(leaves)), encoding="utf-8")
    entries_path.write_text(_entries_include(leaves), encoding="utf-8")
    classes_path.write_text(
        json.dumps(compiler["class_ids"], indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    layout_path.write_text(json.dumps(layout, indent=2) + "\n", encoding="utf-8")
    (output_dir / "statedt_layout.p4inc").write_text(
        _layout_include(layout), encoding="utf-8"
    )
    (output_dir / "statedt_bmv2_type.p4inc").write_text(
        "// Generated StateDT BMv2 entry type. Do not edit by hand.\n"
        f"typedef bit<{int(layout['feature_state_bits']) + 18}> statedt_entry_t;\n",
        encoding="utf-8",
    )
    (output_dir / "statedt_unpack_features.p4inc").write_text(
        _state_access_include(layout, pack=False), encoding="utf-8"
    )
    (output_dir / "statedt_pack_features.p4inc").write_text(
        _state_access_include(layout, pack=True), encoding="utf-8"
    )
    (output_dir / "statedt_update_packet_max.p4inc").write_text(
        _max_update_include(compiler, "Packet Length Max", "packet_length"), encoding="utf-8"
    )
    (output_dir / "statedt_update_fwd_packet_max.p4inc").write_text(
        _max_update_include(compiler, "Fwd Packet Length Max", "packet_length"), encoding="utf-8"
    )
    return model_path, entries_path, classes_path, len(leaves)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate StateDT P4 range-table includes")
    parser.add_argument("compiler", type=Path, help="StateDT compiler.json")
    parser.add_argument(
        "--output-dir", type=Path, default=Path("p4/common"), help="generated include directory"
    )
    args = parser.parse_args()
    model_path, entries_path, classes_path, count = generate(args.compiler, args.output_dir)
    print(
        f"generated {count} StateDT rules: {model_path}, {entries_path}, {classes_path}"
    )


if __name__ == "__main__":
    main()
